
project_id = 'ooqqbplrlgfahuvpcgri'

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[functions.extract-recipe]
verify_jwt = false

[functions.translate-recipe]
verify_jwt = false
