
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooqqbplrlgfahuvpcgri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vcXFicGxybGdmYWh1dnBjZ3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NjI2NDIsImV4cCI6MjA3NTEzODY0Mn0.6vqkM6jcyNmF8kUMgrIS3a3aussb3QYwHDuPHEoRLgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
