// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wujejhoryosljnnappax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1amVqaG9yeW9zbGpubmFwcGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDc1MTUsImV4cCI6MjA1ODU4MzUxNX0.lySCtPI1d8lVMW_NZHxs6RJS57n3sxUtm764GE3510I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);